-- AlterTable
ALTER TABLE "AbsenceRecord" ALTER COLUMN "startDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "endDate" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "AttendanceRecord" ALTER COLUMN "checkIn" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "checkOut" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Employee" ALTER COLUMN "birthdate" SET DATA TYPE DATE,
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "RefreshToken" ALTER COLUMN "expiryDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3);
